### ISSUE TITLE
Change queues to playlists

### ISSUE THREAD

**Issue by hrkfdn** [hrkfdn/ncspot#12]
While it seemed like a good idea in the beginning, it might be necessary to move from queues to real playlists. Queues lose their entries during playback, which might be annoying if you want to save them as a playlist later on.

Instead, maybe the current behavior in the search result view should be changed to have `Space` append them to the playlist and use something like `Shift-Space` to add the selection at the top of the playlist.

**Comment by SafariMonkey** [comment]
I would suggest actually having a "Now Playing" playlist/queue, unlike YouTube (which seems not to have such a concept except when casting). I don't want to create a playlist with permanence every time I want to queue a track. (This can be implemented as an ephemeral playlist, of course.)

**Comment by hrkfdn** [comment]
If I understood this correctly, that would be the way it is implemented now?

**Comment by SafariMonkey** [comment]
Essentially, yes, though it could optionally preserve history. The main thing is not having to manually create a "playlist" in order to play more than one item in sequence. Separating the concept of named, stored playlists and a temporary "now playing" one that things are queued to by default is a good way of doing that IMO.

Playing a playlist can then be implemented in one or both two ways: playing directly from the playlist, or importing the playlist into "now playing". Spotify uses both approaches, so you can "play" an album (for example) and the first track will play and the rest will be will be "next up", and then you can add an album to the "queue", and its tracks will be "next in queue" and play before the subsequent tracks on the album you played first. I'm not convinced that such an approach is necessary in ncspot at this point, so picking one of the two approaches is probably best in my opinion.

**Comment by hrkfdn** [comment]
Oh, the playlist concept I mentioned was meant to imply a temporary playlist. But one that you can save if you like. Similar to how they are implemented in `ncmpc`.
Basically, the only difference would be that during playback the next track is not consumed from a queue, but just taken from a list, while preserving the entire list. This would not require having to create a playlist and at the same time you can preserve the list you build up during your listening session.

**Comment by SafariMonkey** [comment]
That makes sense. Thanks for the clarification. I'll be looking forward to it!

**Comment by im-n1** [comment]
Maybe I can add another point of view.

From what I see in the app and in the code:

Your current queue is ok except one this. It does come from `VecDeque` so you pop out the track once it's played. That not good because you are constantly loosing what has beed played (cannot play a track once again, cannot play music whole day and later that day save it as new spotify playlist,...)
So I guess here the "queue" idea is quite okay.

Once the queue could be saved as new playlist - even better.

Also how @SafariMonkey mentioned. When you "add to queue" track/album/another-playlist in Spotify app you squeeze that after current track in our queue. So if I have 10 tracks in my queue, 5th is now playing and I "add to queue" a track from search its squeezed in between 5th and 6th track so now I have 11 tracks in my queue.

My suggestion is to remove the whole `VecQueue` usage and go with `Vec` instead. You can keep current played track (vec item) index.

Maybe I can help.

**Comment by SafariMonkey** [comment]
> When you "add to queue" track/album/another-playlist in Spotify app you squeeze that after current track in our queue. So if I have 10 tracks in my queue, 5th is now playing and I "add to queue" a track from search its squeezed in between 5th and 6th track so now I have 11 tracks in my queue.

I appreciate the explanation, but that's actually not what I'm saying. In fact, you have two separate things: the "Next In Queue" and the "Next Up". I just tested playing _Album 1_ and then queueing _Album 2_ and then _Album 3_. _Album 1_ starts playing, with its remaining tracks appearing in "Next Up". When I add _Album 2_ to the queue, the "Next In Queue" goes from empty to containing all the tracks in _Album 2_. This means that it will play before any subsequent tracks in _Album 1_, because the queue takes priority over the "Next Up". When I add _Album 3_ to the queue, it is added _after_ the tracks from _Album 2_. If I then just play (not add to queue) _Album 4_, the first track of _Album 4_ starts playing and the "Next Up" is the tracks from _Album 4_ instead of _Album 1_, with _Album 2_ and _Album 3_ still in the queue.

That was a little convoluted, but the gist of it is that there are two sources of tracks: a queue and an autoplay. If you start an album or playlist (or an item from one), it will autoplay tracks from that once the queue has been exhausted.

As for applicability to this software, I think that may be a little overkill unless you want to really match the experience. However, the ability to e.g. both "Add To Queue" and "Queue Next" should IMO cover the main use cases.

**Comment by im-n1** [comment]
Well...I went thru all my spotify app but couldn't find "Next In Queue". What I'm missing?

**Comment by SafariMonkey** [comment]
My guess is your queue is empty, so you're not seeing it. First, you need to add something to your queue by right clicking it and clicking "Add to Queue".

Then, if you click the button (on the bottom right for me) that looks like

```
>--
---
---
```
you should see a view with three sections: "Now Playing", "Next In Queue", and "Next Up".

**Comment by im-n1** [comment]
![image](https://user-images.githubusercontent.com/198654/53802172-74696880-3f41-11e9-9eee-6454ad5821df.png)

Can't see the "Next in Queue".

**Comment by SafariMonkey** [comment]
![image](https://user-images.githubusercontent.com/2837174/53810300-8bfb1e00-3f4e-11e9-8193-ad5a01aa3c7d.png)

As I said in my previous comment, you probably don't have anything in your queue. You need to specifically add a track, album, or playlist to your queue. This is different from just playing them, you need to right click and select "Add to Queue". If you have done those steps and still don't see it, let me know.

**Comment by im-n1** [comment]
Damn you are right. I've been using Spotify for more than ... whole eternity and never noticed this. To be honest it's quite confusing (as you could see above). I guess the whole thing about queue it you have a list of tracks where you can append some to the end and then push some right after currently playing one.

![image](https://user-images.githubusercontent.com/198654/53845263-b679c500-3fa8-11e9-9b85-bfc246b5efa3.png)

I remember good old days of Winamp, where we all had that 50x200px player window and beneath that very long playlist. We d&d some tracks in there and then changed the order because we wanted to play the cool song as next.

Little sum up.

* queue should not remove already played tracks (for later manipulation or just for the info)
* we should have be able to append (to the end) and "squeeze in" (Spotify's "Add to queue" functionality) tracks, albums or even whole playlists.
* we should be able to move tracks in the queue.
* we should be able to select multiple tracks and then move/remove them from the queue.

I guess this is a set of many particular tickets. I just summed the things up.

**Comment by SafariMonkey** [comment]
Yeah, it's definitely a little confusing.

I agree with your points in general. A small nitpick: in Spotify, there seems to be no way of adding an item to the *front* of the queue if it already has items in it. I don't see any reason to replicate that particular fact, though.

Thanks for the summary.
