### ISSUE TITLE
Request: "browse" screen using the genre playlists

### ISSUE THREAD

**Issue by tshirtman** [hrkfdn/ncspot#187]
https://developer.spotify.com/documentation/web-api/reference/browse/get-list-featured-playlists/

**Comment by mtshrmn** [comment]
I've implemented this method myself. I feel like this isn't enough, can you give some feedback on this?

![image](https://user-images.githubusercontent.com/18540571/89132447-ea9a4200-d51c-11ea-9657-5230375ed0b4.png)

**Comment by JojiiOfficial** [comment]
@mtshrmn I'd like to see this feature in the official ncspot application!

**Comment by hrkfdn** [comment]
Hey there, I have added support for category browsing. 

![image](https://user-images.githubusercontent.com/19884/185765029-0cbd6358-d478-4cc1-941a-5e5dc2d0b147.png)

![image](https://user-images.githubusercontent.com/19884/185765021-e7bc2ee2-341f-4d6d-b14c-baaf4b209814.png)

The featured playlists seemed very generic and I only received around 10 lists, so not very interesting, which is why I have skipped them for now. @mtshrmn Did you have the same experience?

**Comment by mtshrmn** [comment]
I don't remember anything about 2 years ago, but it seems to be more than just 10 playlists, it's also consistent over the spotify app on my phone. Looks good to me.

![image](https://user-images.githubusercontent.com/18540571/185792721-88e10a5d-be57-4178-820f-e85157e58d23.png)


PS. please ignore the weird rtl text, im not running a rtl supported terminal

**Comment by hrkfdn** [comment]
Hey! Yeah, the categories are fine. But the featured playlist API only (which ncspot doesn't use currently) returned very few playlists, which is why I was wondering whether I did something wrong.

Anyway, the category browsing seems to work well and has a lot of content, so it's decent enough I suppose :)

**Comment by mtshrmn** [comment]
If I remember correctly, it's related to the token that spotify will allow us to generate. 
They limit a lot of results and the only way to bypass it is by using methods that are against the ToS.

**Comment by hrkfdn** [comment]
Ah, interesting, thanks for sharing
