### ISSUE TITLE
MPRIS track's time 

### ISSUE THREAD

**Issue by r4v3n6101** [hrkfdn/ncspot#223]
KDE's media player show elapsed track's time only when it's opened. 
Seems like ncspot doesn't synchronize time via MPRIS

**Comment by Bettehem** [comment]
I haven't used KDE's media player but at least when using playerctl (which also uses MPRIS) the official Spotify client functions in the same way. You can see the elapsed time of a track for only as long as you monitor it.

**Comment by r4v3n6101** [comment]
I haven't seen such behavior in another implementations of mpris in other players. I think it shouldn't deal in such way. Or it should?

**Comment by Bettehem** [comment]
Nah, it probably shouldn't, but I don't think plasla can do it any better, unless the actual players get updated to support the feature properly

**Comment by Bettehem** [comment]
I have a music bot project where I have had to create a separate counter for elapsed time because Spotify doesn't report it correctly, so technically it is possible, but by having your own separate counter means that it can never be as accurate as it would be if Spotify would properly implement the MPRIS protocol.
That said, I haven't yet tested how ncspot acts in the same scenario, but from what you said it sounds like it does the same thing

**Comment by r4v3n6101** [comment]
I don't understand it. Why do we need separate counter? We have all data, so why it couldn't be calculated? Why do we need to keep it manually?
