### ISSUE TITLE
[Request] Download Songs for Offline Use

### ISSUE THREAD

**Issue by cow-killer** [hrkfdn/ncspot#260]
Could we ever hope to get a feature to download songs from our library in the event our device doesn't have access to the Internet?

**Comment by JojiiOfficial** [comment]
This requires to break spotify's widevine DRM which is against spotify's TOS. Since its 'only' l3 it shouldn't be that hard to do so though. I assume @hrkfdn prefers to keep this application 'legal'. The only alternative I can think of is to 'capture' the output of the sound output from ncspot and encode it to a file. This way you could listen to songs again but not really to download them in a fast way. 

I'd really appreciate a feature to download songs though.

**Comment by hafkensite** [comment]
This is something that the official app does support, up to a certain number of days since last account validation. The cached files are still encrypted on disk, but somehow the key is 'forgotten' after a certain time.
I use a `/etc/hosts` rule to block access to the spotify servers, but ncspot won't start if it cant access them.

**Comment by hrkfdn** [comment]
ncspot uses [librespot](https://github.com/librespot-org/librespot) to handle Spotify sessions and music playback. librespot currently does not support offline sessions or playback and it couldn't be implemented on ncspot side, either.

**Comment by hrkfdn** [comment]
Closed as it can't be implemented within ncspot
