### ISSUE TITLE
[mpris] Play State bouncing

### ISSUE THREAD

**Issue by jdost** [hrkfdn/ncspot#395]
**Version**: 0.3.0

## What is seen

When playing tracks, the MPRIS play state bounces when changing tracks.  What I mean is that when a track finishes and the next track starts, MPRIS reports the player `stopped` and then immediately `playing` after.

I see this by using the [`playerctl`](https://github.com/altdesktop/playerctl) MPRIS helper in monitor mode (`playerctl -a -F metadata -f '{{lc(status)}} - {{playerName}}'`) and when playing through a playlist the output looks like:
```
playing - ncspot
stopped - ncspot
playing - ncspot
stopped - ncspot
playing - ncspot
```

## What I expect

When the playing starts, a `playing` status is broadcast and then `stopped` is only broadcast when the queue is empty (i.e. there is no next track to play).  This is the behavior in other music players (this is playing through a three track playlist):
```
playing - cmus
stopped - cmus
```

**Comment by Bettehem** [comment]
I think it's very helpful to get notified after each track ends.
I have been creating a ts3 music bot with spotify support among others, and the way I have done it is to hold a separate list of songs you want to play, and then I can just use mpris' OpenUri function to start each track at will. Its easy to implent like this, compared to the alternative, which is that you'd have to check the song's duration and position to determine wether a song has ended. This would be good otherwise, but for example if using the official Spotify client, the position readings it returns when a track is playing are inconsistent at best. Not sure if ncspot has the same problem though.
Anyway, If ncspot does reports the track's position consitently, then the idea of only getting `Stopped` at the end of the queue instead of each track could be a welcome change.
In the meanwhile you can workaround this by just having yor tracks in a list somewhere, and after getting the status back as `Stopped`, you can just use mpris' OpenUri function to start the next track in your list.

**Comment by Bettehem** [comment]
I think it's very helpful to get notified after each track ends.
I have been creating a ts3 music bot with spotify support among others, and the way I have done it is to hold a separate list of songs you want to play, and then I can just use mpris' OpenUri function to start each track at will. Its easy to implent like this, compared to the alternative, which is that you'd have to check the song's duration and position to determine wether a song has ended. This would be good otherwise, but for example if using the official Spotify client, the position readings it returns when a track is playing are inconsistent at best. Not sure if ncspot has the same problem though.
Anyway, If ncspot does reports the track's position consitently, then the idea of only getting `Stopped` at the end of the queue instead of each track could be a welcome change.
In the meanwhile you can workaround this by just having yor tracks in a list somewhere, and after getting the status back as `Stopped`, you can just use mpris' OpenUri function to start the next track in your list.

**Comment by jdost** [comment]
@Bettehem For your use case, if you only enqueue a single track, it *should* still change state to `Stopped` when the play queue is exhausted, my statement is that it bounces from `Stopped` to `Playing` while still working through the queue. So anything that is monitoring for active players (my usecase) will see that ncspot has finished playing and rotate to another active MPRIS app.

**Comment by Bettehem** [comment]
Oh I see. Yeah It would probably make sense to change the state being `Stopped` only after the queue ends.
