### ISSUE TITLE
Security issue: anyone can access spotify credentials as they are stored clean-text

### ISSUE THREAD

**Issue by TheCapsLock** [hrkfdn/ncspot#447]
Credentials are stored in `~/.config/ncspot/credentials.toml`; `username` contains the `email` of the spotify account ; `auth_data` contains the `password` of the spotify account encoded in `base64`.

Anyone can access those credentials as long as they are the owner of the file (eg any process ran by current user on the OS.

**Comment by hrkfdn** [comment]
Yes, it's not ideal, any suggestions for a better approach? The only other approach I see is only keeping the Spotify session token and have users re-login when it expires.

**Comment by Qluxzz** [comment]
Can't find the code that does it right now, but the daemon for Transmission encrypts the password entered in the settings file and overwrites it with the encrypted password instead. So on subsequent uses, it uses the encrypted password instead of your real password.

Since the user enters it themself when starting the program, we should be able to encrypt it directly and only ever store the encrypted password in credentials.toml.

**Comment by hrkfdn** [comment]
I don't know what Transmission uses the password for, but with ncspot the problem is that librespot needs the password in cleartext to create a Spotify session. That means if the token has expired, we'd need to decrypt the password so I can pass it as cleartext again, which renders it very ineffective.

So as far as I can tell the only more secure way would be to keep the token and then have the user login again once it expires.

**Comment by Qluxzz** [comment]
Yeah I guess its really security by obscurity, but it would help us not
storing the password in clear text in the config files, but allowing access
to the password internally in ncspot, as we need when authenticating with
librespot.

So on subsequent runs we decrypt the encrypted password and use it as
before. But we never store the password on disk.

It would be nice if the salt could be programmatically generated and unique
to each install as well.

Transmission uses it for all passwords in the config files, such as the
password for the RPC.

I'll look through the source code for Transmission more tomorrow and see if
I can find how they generate the salt or if its hardcoded.



Another way entirely might be to use the integrated keychain for
authentication instead of the usercredentials file.

It's usually automatically unlocked on login in so the user wouldn't need
to reenter the password.
