### ISSUE TITLE
ncspot crashes unexpectedly while searching for playlists

### ISSUE THREAD

**Issue by epixinvites** [hrkfdn/ncspot#455]
[output.txt](https://github.com/hrkfdn/ncspot/files/6061777/output.txt)
I attached the debug log for reference. I searched for "Lofi" in the searching tab and then it worked fine until I moved over to "Playlists" and then it just crashed unexpectedly.

**Comment by hrkfdn** [comment]
Could you also upload an stderr log, e.g. by logging it via `RUST_BACKTRACE=full ncspot -d debug.log 2> stderr.log`, preferably from a debug build.

**Comment by epixinvites** [comment]
after running that command, apparently nothing is logged into stderr.log

**Comment by BachoSeven** [comment]
@epixinvites Are you sure this is not an issue with your terminal and Emoji fonts? i.e. `st` does not support emojis out of the box, and not all terminals do.

P.S. I am only asking this because a few months ago I would have `ncspot` crashing similarly also when looking for lofi songs, since those playlists always have emojis :P

**Comment by hrkfdn** [comment]
Good point, would be interesting to know whether or the terminal crashes.

**Comment by epixinvites** [comment]
I'm using `st` running on /bin/zsh on Arch

**Comment by BachoSeven** [comment]
Exactly, so it's very likely that your issue is unrelated to `ncspot`, but rather due to `st` not handling emojis well.

For more info about the `Xft` bug which causes this, see [this](https://git.suckless.org/st/file/FAQ.html#l224) section of the `st` official FAQ.
If you want to make `st` handle emojis, you will need to install a version of `libxft` with [this](https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/1) patch; since you're on Arch you can get it from the [AUR](https://aur.archlinux.org/packages/libxft-bgra/). 
Hope this helps!

P.S. feel free to close this, since it's not an issue with ncspot

**Comment by epixinvites** [comment]
Yeap, it works after I switched to a more modern terminal. Thanks!
