### ISSUE TITLE
Pressing quit while in login causes a panic

### ISSUE THREAD

**Issue by HoolaBoola** [hrkfdn/ncspot#479]
First time trying the program, pressed the "Quit" button in the login screen, which causes the process to panic:
```
thread 'main' panicked at 'Could not create credentials: "Didn\'t obtain any credentials"', /home/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.5.0/src/main.rs:118:42
```

This is mainly a cosmetic bug, as while panics aren't really supposed to be shown to the user(?), the program did what I wanted it to do - quit

**Comment by ChaboCode** [comment]
It's important for the devs to know if a login was sucessful or not. An aesthetic solution may be printing the message on a log file instead of the screen. I haven't read the code so I don't know if there's already a log file, maybe @hrkfdn can say someting about this.

(Sorry if some words are weird, my english is not the best)

**Comment by HoolaBoola** [comment]
The obvious solution would be to just print 
> Could not create credentials: "Didn't obtain any credentials"
Or 
> Login canceled
Or something along those lines
