### ISSUE TITLE
Persist sorting orders for playlists is not working since 0.6

### ISSUE THREAD

**Issue by bemug** [hrkfdn/ncspot#497]
**Describe the bug**
Since 0.6 the "Persist sorting orders for playlists (#436)" is not working anymore. Was working fine in 0.5.

**To Reproduce**
1. Go to a playlist
2. Sort by added desc for example
3. Close ncspot
4. Go to the same playlist

**Expected behavior**
The playlist should keep the sort setting from earlier.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Linux
 - Terminal: urxvt
 - Version: 0.6
 - Installed from: AUR

**Backtrace/Debug log**
N/A

**Additional context**
N/A

**Comment by Pulkit12083** [comment]
A follow up on this: is the sort command working at all?
---------------------------
Issue:
`sort added desc` returns `"ERROR: Unknown command"` (similar with d, descending, a, asc, ascending)
`sort` does nothing.

Specs:
OS: Ubuntu 20.04.2.
Installed from: Apt
----
It's possibly my usage is wrong. Please let me know if so?

**Comment by Pulkit12083** [comment]
Hi @hrkfdn 
This is unrelated to the above bug but I was curious if there are any plans to add sorting to lists that aren't playlists. (sorting list of Albums, Tracks by sort_params like "added"). It might be a really useful/intuitive feature since few people listen to their music by alphabetical listing.

PS: thanks for the client, it's really cool.

**Comment by bemug** [comment]
I can't reproduce it anymore. No idea what happened.

I'm closing this, sorry for the noise.
