### ISSUE TITLE
armf and arm64 linux builds for Raspberry Pi

### ISSUE THREAD

**Issue by j-maynard** [hrkfdn/ncspot#659]
**Is your feature request related to a problem? Please describe.**
No ARM builds for the Raspberry Pi. 

**Describe the solution you'd like**
ARM Builds for the Raspberry Pi 

**Describe alternatives you've considered**
I can build myself but being able to just download it would speed up setting up a new Pi and I wouldn't have to install rust any more.

**Comment by diadras** [comment]
I was unable to get a build. Mainly because I have never used Rust and ran against errors.
I assume you were able to get a build for an RPI running on an arm64 processor? Could you tell me how?

I didn't get very far, I was unable to figure out how to get a proper Cargo.toml file for the build, getting stuck at `could not find Cargo.toml` or `couldn't read rest.rs`

Thanks :)

**Comment by diadras** [comment]
Update; Figured out I tried to build the binary from releases, not the whole repo itself. I downloaded the repo and am compiling the application.

**Comment by diadras** [comment]
Update2; Compiling would freeze my Pi 4 at `38x/390: reqwest`. I would try a nohup (because maybe it was the ssh session?) and check when the lights would stop flashing but the nohup.out would show errors after the compile. I then tried the command cargo install ncspot and it would compile again and fail. After the last attempt it bricked the OS so I am reinstalling :)

**Comment by diadras** [comment]
Last and final update. I bricked my RPI4. It now boots with a solid red and green light. Forum posts show it is a well known problem and I need to RMA. Sadly this RPI is kinda old so no RMA for this one 🤷 
I hope my finding will help someone!

**Comment by hrkfdn** [comment]
@diadras Oof, that sucks. Did it brick because of excessive load? Doesn't sound like something that should happen. I have set up a CI flow to build for arm64 at least, but I couldn't test it yet.

**Comment by hrkfdn** [comment]
Binary is here: https://github.com/hrkfdn/ncspot/releases/tag/v0.9.3

**Comment by j-maynard** [comment]
@diadras I managed to build and run it on my Raspberry Pi 4 (8GB) the other day, took a little while but it did build.

**Comment by hrkfdn** [comment]
@j-maynard @diadras would one of you be able to test the arm64 binary? or do you run armhf?

**Comment by hrkfdn** [comment]
There are `armhf` binaries as well now :)

**Comment by j-maynard** [comment]
I can confirm the armhf binary works on my Pi400... I am just organising a 64bit install on rasbian now and I'll then test the 64bit version to...  In any event... Thank you ever so much for doing this... Its awesome!

**Comment by hrkfdn** [comment]
Awesome, thanks for confirming, glad it works :)

**Comment by j-maynard** [comment]
I can confirm the 64bit version works as well on Pi400 and Pi4... This is awesome... Thank you! :-D

**Comment by hrkfdn** [comment]
That's great, thank you :)
