### ISSUE TITLE
Periodically save state

### ISSUE THREAD

**Issue by languitar** [hrkfdn/ncspot#948]
**Is your feature request related to a problem? Please describe.**

Currently, ncspot only saves its state on proper termination using `q`. In my setup, ncspot is launched automatically on session start and terminated when the system is powered off. In this case, the terminal containing is closed and no proper termination seems to happen. Therefore, ncspot always comes up after boot with an old state.

**Describe the solution you'd like**

Periodically save the current state such that something reasonable reappears after improper termination.

**Describe alternatives you've considered**

Maybe there's also a chance to install more signal handlers that save the session state.

**Additional context**

* Terminal atm: foot

**Comment by ThomasFrans** [comment]
On Linux, this could be done with the [Systemd logind crate](https://docs.rs/logind-zbus/latest/logind_zbus/) I think (for systems that use Systemd as init system). I don't know if there is already a crate that abstracts this for other platforms. I would also really like this functionality because ncspot is kind of always in the background, playing music, doing its thing, and it would be nice if it shouldn't have to be explicitly closed, but could just react to shutdown events and properly exit.

**Comment by hrkfdn** [comment]
Saving on `SIGTERM` would probably be a good start

**Comment by hrkfdn** [comment]
Hey @languitar, I have added a `SIGTERM` handler. Please let me know if it helps :)

**Comment by languitar** [comment]
Thanks for the quick response. Unfortunately, SIGTERM doesn't seem to be enough to handle the case of a closing terminal. Probably, SIGHUP handling is needed here:

> Hangup detected on controlling terminal  or death of controlling process

From `man 7 signal`.

**Comment by hrkfdn** [comment]
@languitar Makes sense, I have added `SIGHUP` handling as well.

**Comment by languitar** [comment]
Thanks. That works!

**Comment by languitar** [comment]
Is there a chance to push out a new release including the fix for this issue?

**Comment by hrkfdn** [comment]
@languitar Just pushed out a new release
