### ISSUE TITLE
Add Ctrl+d, Ctrl+u (like Vim) and change d to x

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#959]
**Is your feature request related to a problem? Please describe.**
It would be nice to have ctrl+d and ctrl+u to quickly go through larger playlists. I could make a PR that adds this, but I wanted to ask about this first. Also the current d should maybe be moved to x if this was implemented to avoid deleting songs by accident. (x is delete character in Vim, so ig a song could be considered "the smallest unit of Spotify" :wink: ).

**Comment by Bettehem** [comment]
Hi, I'd like to give my opinion.
As a vim user I'm quite interested in your idea and the ctrl+d & ctrl+u sounds good, maybe even ctrl+e and ctrl+y could be added as well, but I think `d` should remain as the delete button. In vim `dd` deletes a line, so it's quite straight forward if you think of it like that. I'm not sure if changing such an essential key at this point might just cause more confusion than help? Also you could change the keybinding to `x` or whatever you want by using [custom keybindings](https://github.com/hrkfdn/ncspot#key-bindings), so you could change those to make it use even more vim-like buttons if you feel like it.

As for the idea with `d` changing to `x` because a song could be considered the smallest unit of spotify; this works well for songs, but you can use the same `d` button to delete albums, artists, playlists, podcasts etc. so that reasoning wouldn't work for any of the other types (except for podcast episodes).
